version: '3'
services:
  php:
    image: 'chialab/php-dev:7.2-apache'
    ports:
      - '80:80'
    volumes:
      - './:/var/www'
      - './development/docker/vhost.conf:/etc/apache2/sites-enabled/000-default.conf'
      - './development/docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini'
      - './development/docker/php/scripts:/scripts'
    entrypoint:
      - bash
      - /scripts/entrypoint.sh
    restart: on-failure
    working_dir: /var/www/html
    depends_on:
      - mysql
  mysql:
    image: 'mysql:5.7'
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: example
      MYSQL_ROOT_PASSWORD: buzzwoo
    volumes:
      - 'db:/var/lib/mysql'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=buzzwoo
    restart: always
    ports:
      - '8080:80'
volumes:
  db: {  }
